// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJbu6qTh9oJVyAl_-b_CxpgL8D7-G9YSc',
    appId: '1:401508023931:web:226b11d01697dda72a2cde',
    messagingSenderId: '401508023931',
    projectId: 'geofriends-c5fd9',
    authDomain: 'geofriends-c5fd9.firebaseapp.com',
    storageBucket: 'geofriends-c5fd9.appspot.com',
    measurementId: 'G-EF46X55JLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3WNgsWyjqplTgffopwAjMyY1JSsz66mU',
    appId: '1:401508023931:android:f5f02ad90c97b2fd2a2cde',
    messagingSenderId: '401508023931',
    projectId: 'geofriends-c5fd9',
    storageBucket: 'geofriends-c5fd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUfn84zsvNabzHxJ0h2dEN3vC1hbGw6o',
    appId: '1:401508023931:ios:8a4fc91308c68a532a2cde',
    messagingSenderId: '401508023931',
    projectId: 'geofriends-c5fd9',
    storageBucket: 'geofriends-c5fd9.appspot.com',
    iosClientId: '401508023931-faack89l4uut1a0fc8he83a3o4s3escp.apps.googleusercontent.com',
    iosBundleId: 'com.example.somt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABUfn84zsvNabzHxJ0h2dEN3vC1hbGw6o',
    appId: '1:401508023931:ios:8a4fc91308c68a532a2cde',
    messagingSenderId: '401508023931',
    projectId: 'geofriends-c5fd9',
    storageBucket: 'geofriends-c5fd9.appspot.com',
    iosClientId: '401508023931-faack89l4uut1a0fc8he83a3o4s3escp.apps.googleusercontent.com',
    iosBundleId: 'com.example.somt',
  );
}
